# -*- coding: utf-8 -*-
"""maware2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BlSrn_pD8PI0Z8sMBAUQI3gV3D96G6so
"""

# ===================== CELL 1: download DAPT 2020 + deps =====================
!pip -q install shap xgboost scipy scikit-learn 2>/dev/null
!apt-get -qq install git-lfs >/dev/null 2>&1; git lfs install >/dev/null 2>&1

import os, glob
REPO = "/content/dapt2020"
if not os.path.isdir(REPO):
    !git clone https://gitlab.com/asu22/dapt2020.git {REPO}
    !cd {REPO} && git lfs pull 2>/dev/null || true

csvs = sorted(glob.glob(REPO + "/**/*.csv", recursive=True))
print(f"Found {len(csvs)} CSV files under {REPO}:")
for c in csvs:
    print(f"  {os.path.getsize(c)/1e6:7.1f} MB  {c}")
assert csvs, "No CSVs found — check the clone / git-lfs pull."
os.environ["DAPT_REPO"] = REPO

# ===================== CELL 2: corrected MambaKAN-APT pipeline ================
# REAL DAPT 2020 only. No synthetic data. Honest exfiltration handling.
import os, glob, time, warnings, numpy as np, pandas as pd, torch
import torch.nn as nn, torch.nn.functional as F
from sklearn.metrics import classification_report, accuracy_score, f1_score
from sklearn.model_selection import StratifiedShuffleSplit
from scipy import stats
warnings.filterwarnings("ignore")

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", DEVICE, "| torch", torch.__version__)

# ----------------------------- CONFIG ---------------------------------------
REPO       = os.environ.get("DAPT_REPO", "/content/dapt2020")
SEEDS      = [0, 1, 2, 3, 4]      # for mean±std + significance
EPOCHS     = 25
BATCH      = 512
SEQ_LEN    = 8                    # main sequence length
L_SWEEP    = [4, 8, 16]           # reviewer-requested L sweep (MambaKAN only)
TEST_FRAC  = 0.20
CLASS_NAMES = ["Normal", "Reconnaissance", "Foothold",
               "Lateral_Movement", "Data_Exfiltration"]
STAGE_MAP = {"benign":0,"normal":0,"reconnaissance":1,"establish foothold":2,
             "foothold":2,"lateral movement":3,"data exfiltration":4}
DAY_ORDER = {"monday":0,"tuesday":1,"wednesday":2,"thursday":3,"friday":4}
NON_FEATURE = {"Flow ID","Src IP","Source IP","Src Port","Source Port","Dst IP",
               "Destination IP","Dst Port","Destination Port","Protocol",
               "Timestamp","Activity","Stage","Label"}

# ----------------------- 1. LOAD + CLEAN REAL DATA --------------------------
def canonical_cols(files):
    for f in files:
        with open(f, "r", errors="replace") as fh:
            if fh.readline().split(",")[0].strip() == "Flow ID":
                return [c.strip() for c in pd.read_csv(f, nrows=0).columns]
    raise RuntimeError("No CSV with a 'Flow ID' header found.")

def day_of(fname):
    low = fname.lower()
    return next((d for d in DAY_ORDER if d in low), "unknown")

def load_raw():
    files = sorted(glob.glob(REPO + "/**/*.csv", recursive=True))
    canon = canonical_cols(files); frames = []
    for f in files:
        with open(f, "r", errors="replace") as fh:
            has_hdr = fh.readline().split(",")[0].strip() == "Flow ID"
        if has_hdr:
            df = pd.read_csv(f, low_memory=False)
            df.columns = [c.strip() for c in df.columns]
        else:                                   # header-less pvt-thursday
            df = pd.read_csv(f, header=None, low_memory=False)
            if df.shape[1] != len(canon):
                continue
            df.columns = canon
        if "Stage" not in df.columns:
            continue
        df["day"] = day_of(os.path.basename(f))
        frames.append(df)
        print(f"  loaded {os.path.basename(f):40s} rows={len(df):6d} hdr={has_hdr}")
    return pd.concat(frames, ignore_index=True)

df = load_raw()
raw = df["Stage"].astype(str).str.strip().str.lower()
unknown = sorted(set(raw) - set(STAGE_MAP))
assert not unknown, f"Unmapped Stage values: {unknown}"
y_all  = raw.map(STAGE_MAP).astype(int).values
day_all = df["day"].map(DAY_ORDER).fillna(-1).astype(int).values
feat_cols = [c for c in df.columns if c not in NON_FEATURE and c != "day"]
X_all = df[feat_cols].apply(pd.to_numeric, errors="coerce")
X_all = X_all.replace([np.inf,-np.inf], np.nan).fillna(0.0).astype(np.float32).values
keep = X_all.std(0) > 0
X_all, feat_cols = X_all[:,keep], [c for c,k in zip(feat_cols,keep) if k]
F_DIM = X_all.shape[1]
print(f"\nflows={X_all.shape}, informative_features={F_DIM}")
print("class dist:", {CLASS_NAMES[i]: int((y_all==i).sum()) for i in range(5)})

# ------------------- 2. CAUSAL PER-FLOW WINDOWS (within-day) ----------------
def causal_windows(X, y, day, L):
    """Every flow becomes a target; context = up to L preceding flows in same day."""
    N = len(X); Xs = np.zeros((N, L, X.shape[1]), np.float32)
    for d in sorted(set(day.tolist())):
        idx = np.where(day == d)[0]; Xd = X[idx]
        for j, gi in enumerate(idx):
            s = max(0, j-L+1); win = Xd[s:j+1]
            if len(win) < L:
                win = np.concatenate([np.repeat(Xd[s:s+1], L-len(win), 0), win], 0)
            Xs[gi] = win
    return Xs, y.copy()

def zscore_fit(tr):
    f = tr.reshape(-1, tr.shape[-1]); mu, sd = f.mean(0), f.std(0); sd[sd<1e-8]=1.0
    return mu, sd
def zscore_apply(a, mu, sd): return ((a-mu)/sd).astype(np.float32)

# ----------------------------- 3. MODELS ------------------------------------
class BSpline(nn.Module):
    def __init__(s, n=8, d=3):
        super().__init__(); s.d=d; s.n=n
        s.register_buffer("k", torch.linspace(-1,1,n+d+1))
    def forward(s, x):
        x=x.unsqueeze(-1); k=s.k; b=((x>=k[:-1])&(x<k[1:])).float()
        for j in range(1, s.d+1):
            ln=x-k[:-(j+1)]; ld=(k[j:-1]-k[:-(j+1)]).clamp(min=1e-8)
            rn=k[j+1:]-x;     rd=(k[j+1:]-k[1:(-j if j>0 else None)]).clamp(min=1e-8)
            b=(ln/ld)*b[...,:-1]+(rn/rd)*b[...,1:]
        return b
class KANLayer(nn.Module):
    def __init__(s, i, o, n=8):
        super().__init__(); s.bs=BSpline(n); s.c=nn.Parameter(torch.randn(i,o,n)*0.1)
        s.lin=nn.Linear(i,o); s.nm=nn.LayerNorm(o)
    def forward(s, x):
        sp=torch.einsum("bin,ion->bo", s.bs(torch.tanh(x)), s.c)
        return s.nm(sp + F.silu(s.lin(x)))
class KANEncoder(nn.Module):
    def __init__(s, i, dims=(128,96,64), n=8):
        super().__init__(); L=[]; p=i
        for h in dims: L+= [KANLayer(p,h,n), nn.Dropout(0.15)]; p=h
        s.net=nn.Sequential(*L); s.out=dims[-1]
    def forward(s,x): return s.net(x)
class SelectiveSSM(nn.Module):
    def __init__(s, dm=64, ds=16, dc=4, ex=2):
        super().__init__(); s.di=dm*ex; s.ds=ds
        s.inp=nn.Linear(dm,s.di*2,bias=False)
        s.cv=nn.Conv1d(s.di,s.di,dc,padding=dc-1,groups=s.di,bias=True)
        s.xp=nn.Linear(s.di,ds*2+1,bias=False); s.dtp=nn.Linear(1,s.di,bias=True)
        A=torch.arange(1,ds+1,dtype=torch.float32).unsqueeze(0).expand(s.di,-1)
        s.Al=nn.Parameter(torch.log(A.clone())); s.D=nn.Parameter(torch.ones(s.di))
        s.op=nn.Linear(s.di,dm,bias=False); s.nm=nn.LayerNorm(dm)
    def forward(s, x):
        B,L,_=x.shape; res=x; xz=s.inp(x); xc,z=xz.chunk(2,-1)
        xc=s.cv(xc.transpose(1,2))[:,:,:L].transpose(1,2); xc=F.silu(xc)
        p=s.xp(xc); Bp=p[:,:,:s.ds]; Cp=p[:,:,s.ds:2*s.ds]
        dt=F.softplus(s.dtp(p[:,:,-1:])); A=-torch.exp(s.Al)
        h=torch.zeros(B,s.di,s.ds,device=x.device); outs=[]
        for t in range(L):                       # TRUE selective recurrence
            dA=torch.exp(A.unsqueeze(0)*dt[:,t,:].unsqueeze(-1))
            dB=dt[:,t,:].unsqueeze(-1)*Bp[:,t,:].unsqueeze(1)
            h=dA*h+dB*xc[:,t,:].unsqueeze(-1)
            outs.append((h*Cp[:,t,:].unsqueeze(1)).sum(-1)+s.D*xc[:,t,:])
        y=torch.stack(outs,1)*F.silu(z)
        return s.nm(s.op(y)+res)
class MambaBlock(nn.Module):
    def __init__(s, dm=64, ds=16):
        super().__init__(); s.ssm=SelectiveSSM(dm,ds)
        s.ffn=nn.Sequential(nn.Linear(dm,dm*2),nn.GELU(),nn.Dropout(0.1),
                            nn.Linear(dm*2,dm),nn.Dropout(0.1)); s.nm=nn.LayerNorm(dm)
    def forward(s,x): x=s.ssm(x); return s.nm(x+s.ffn(x))
class MambaKAN(nn.Module):
    def __init__(s, i, nc=5, L=8, dims=(128,96,64), n=8, nl=3, ds=16):
        super().__init__(); s.enc=KANEncoder(i,dims,n); s.dm=dims[-1]
        s.pos=nn.Parameter(torch.randn(1,L,s.dm)*0.02)
        s.mb=nn.ModuleList([MambaBlock(s.dm,ds) for _ in range(nl)])
        s.cl=nn.Sequential(nn.Linear(s.dm*2,128),nn.GELU(),nn.Dropout(0.2),
                           nn.Linear(128,64),nn.GELU(),nn.Dropout(0.15),nn.Linear(64,nc))
    def feats(s, x):
        B,L,Fd=x.shape; e=s.enc(x.reshape(B*L,Fd)).reshape(B,L,-1)+s.pos[:,:L,:]
        for m in s.mb: e=m(e)
        return torch.cat([e.mean(1), e.max(1).values],-1)
    def forward(s,x): return s.cl(s.feats(x))
class SAE(nn.Module):
    def __init__(s,i,nc=5):
        super().__init__(); s.e=nn.Sequential(nn.Linear(i,128),nn.ReLU(),nn.Dropout(0.1),
            nn.Linear(128,64),nn.ReLU(),nn.Dropout(0.1),nn.Linear(64,32),nn.ReLU()); s.c=nn.Linear(32,nc)
    def forward(s,x):
        if x.dim()==3: x=x[:,-1,:]
        return s.c(s.e(x))
class LSTM_SAE(nn.Module):
    def __init__(s,i,nc=5):
        super().__init__(); s.l=nn.LSTM(i,64,2,batch_first=True,dropout=0.1,bidirectional=True)
        s.c=nn.Sequential(nn.Linear(128,64),nn.ReLU(),nn.Dropout(0.2),nn.Linear(64,nc))
    def forward(s,x):
        if x.dim()==2: x=x.unsqueeze(1)
        o,_=s.l(x); return s.c(o[:,-1,:])
class TransformerDet(nn.Module):
    def __init__(s,i,nc=5):
        super().__init__(); s.p=nn.Linear(i,64)
        s.t=nn.TransformerEncoder(nn.TransformerEncoderLayer(64,4,128,0.1,batch_first=True),3)
        s.c=nn.Sequential(nn.Linear(64,64),nn.ReLU(),nn.Dropout(0.2),nn.Linear(64,nc))
    def forward(s,x):
        if x.dim()==2: x=x.unsqueeze(1)
        return s.c(s.t(s.p(x)).mean(1))
class FocalLoss(nn.Module):
    def __init__(s,a=None,g=2.0): super().__init__(); s.a=a; s.g=g
    def forward(s,o,t):
        ce=F.cross_entropy(o,t,weight=s.a,reduction="none"); pt=torch.exp(-ce)
        return (((1-pt)**s.g)*ce).mean()

TORCH_MODELS = {"MambaKAN-APT":MambaKAN,"SAE":SAE,"LSTM-SAE":LSTM_SAE,"Transformer":TransformerDet}

# ----------------------------- 4. TRAIN/EVAL -------------------------------
def make_model(name, L):
    return (MambaKAN(F_DIM, L=L) if name=="MambaKAN-APT" else TORCH_MODELS[name](F_DIM)).to(DEVICE)

def train_eval_torch(name, Xtr, ytr, Xte, yte, L, seed):
    torch.manual_seed(seed); np.random.seed(seed)
    m = make_model(name, L)
    cw = torch.tensor([len(ytr)/(5*max(1,(ytr==c).sum())) for c in range(5)],
                      dtype=torch.float32, device=DEVICE)
    crit = FocalLoss(cw, 2.0)
    opt = torch.optim.AdamW(m.parameters(), lr=1e-3, weight_decay=1e-4)
    sch = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=EPOCHS, eta_min=1e-6)
    Xtr_t = torch.tensor(Xtr); ytr_t = torch.tensor(ytr)
    n=len(Xtr_t)
    for ep in range(EPOCHS):
        m.train(); perm=torch.randperm(n)
        for i in range(0,n,BATCH):
            b=perm[i:i+BATCH]; xb=Xtr_t[b].to(DEVICE); yb=ytr_t[b].to(DEVICE)
            opt.zero_grad(); loss=crit(m(xb), yb); loss.backward()
            nn.utils.clip_grad_norm_(m.parameters(),1.0); opt.step()
        sch.step()
    m.eval(); preds=[]
    with torch.no_grad():
        Xte_t=torch.tensor(Xte)
        for i in range(0,len(Xte_t),BATCH):
            preds.append(m(Xte_t[i:i+BATCH].to(DEVICE)).argmax(1).cpu().numpy())
    return np.concatenate(preds), m

def train_eval_xgb(Xtr, ytr, Xte, yte, seed):
    import xgboost as xgb
    clf=xgb.XGBClassifier(n_estimators=400,max_depth=8,learning_rate=0.1,
        subsample=0.8,colsample_bytree=0.8,tree_method="hist",device=DEVICE,
        objective="multi:softprob",num_class=5,eval_metric="mlogloss",random_state=seed)
    clf.fit(Xtr.reshape(len(Xtr),-1), ytr)
    return clf.predict(Xte.reshape(len(Xte),-1)), clf

def metrics(yte, pred):
    rep=classification_report(yte,pred,labels=list(range(5)),
        target_names=CLASS_NAMES,output_dict=True,zero_division=0)
    return {"acc":accuracy_score(yte,pred),
            "f1_macro":f1_score(yte,pred,average="macro",zero_division=0),
            "f1_weighted":f1_score(yte,pred,average="weighted",zero_division=0),
            "report":rep}

# ---- build windows once at SEQ_LEN ----
print(f"\nbuilding causal windows (L={SEQ_LEN}) ...")
Xw, yw = causal_windows(X_all, y_all, day_all, SEQ_LEN)
print("windows:", Xw.shape)

# =================== PROTOCOL A: stratified 5-seed CV ======================
print("\n" + "="*70)
print("PROTOCOL A — stratified hold-out, 5 seeds (mean±std).")
print("NOTE: causal windows overlap, so this slightly favors all models")
print("equally; reported alongside the leakage-free day-holdout below.")
print("="*70)
ALL = ["MambaKAN-APT","SAE","LSTM-SAE","Transformer","XGBoost"]
res = {k:{"acc":[],"f1_macro":[],"f1_weighted":[],"exfil_recall":[]} for k in ALL}
last_report = {}
for seed in SEEDS:
    sss=StratifiedShuffleSplit(1, test_size=TEST_FRAC, random_state=seed)
    tr,te=next(sss.split(Xw,yw))
    mu,sd=zscore_fit(Xw[tr]); Xtr=zscore_apply(Xw[tr],mu,sd); Xte=zscore_apply(Xw[te],mu,sd)
    ytr,yte=yw[tr],yw[te]
    for name in ALL:
        t0=time.time()
        if name=="XGBoost": pred,_=train_eval_xgb(Xtr,ytr,Xte,yte,seed)
        else:               pred,_=train_eval_torch(name,Xtr,ytr,Xte,yte,SEQ_LEN,seed)
        mt=metrics(yte,pred)
        res[name]["acc"].append(mt["acc"]); res[name]["f1_macro"].append(mt["f1_macro"])
        res[name]["f1_weighted"].append(mt["f1_weighted"])
        res[name]["exfil_recall"].append(mt["report"]["Data_Exfiltration"]["recall"])
        last_report[name]=mt["report"]
        print(f"  seed {seed} {name:14s} acc={mt['acc']:.4f} f1m={mt['f1_macro']:.4f} "
              f"exfilR={mt['report']['Data_Exfiltration']['recall']:.3f} ({time.time()-t0:.0f}s)")

print("\n----- PROTOCOL A SUMMARY (mean ± std over %d seeds) -----" % len(SEEDS))
print(f"{'model':14s} {'accuracy':>16s} {'macro-F1':>16s} {'weighted-F1':>16s} {'exfil recall':>16s}")
for name in ALL:
    a=np.array(res[name]["acc"]); fm=np.array(res[name]["f1_macro"])
    fw=np.array(res[name]["f1_weighted"]); er=np.array(res[name]["exfil_recall"])
    print(f"{name:14s} {a.mean():.4f}±{a.std():.4f}  {fm.mean():.4f}±{fm.std():.4f}  "
          f"{fw.mean():.4f}±{fw.std():.4f}  {er.mean():.3f}±{er.std():.3f}")

# significance: MambaKAN macro-F1 vs strongest baseline
base=[b for b in ALL if b!="MambaKAN-APT"]
best=max(base, key=lambda b: np.mean(res[b]["f1_macro"]))
t,p=stats.ttest_rel(res["MambaKAN-APT"]["f1_macro"], res[best]["f1_macro"])
print(f"\nSignificance (paired t-test, macro-F1): MambaKAN-APT vs {best}: "
      f"t={t:.3f}, p={p:.4f}  (n={len(SEEDS)} seeds)")
print("\nPer-class (last seed, MambaKAN-APT) — note SUPPORT counts:")
for c in CLASS_NAMES:
    r=last_report["MambaKAN-APT"][c]
    print(f"  {c:18s} P={r['precision']:.3f} R={r['recall']:.3f} F1={r['f1-score']:.3f} support={int(r['support'])}")

# =============== PROTOCOL B: leakage-free day-holdout =======================
print("\n" + "="*70)
print("PROTOCOL B — day-holdout: train Mon–Thu, test Fri (zero leakage).")
print("Exfiltration occurs ONLY on Fri, so it is absent from training — the")
print("model cannot learn it. This is the honest dataset limitation that")
print("refutes any 'exfiltration breakthrough' claim.")
print("="*70)
tr_mask=np.isin(day_all,[0,1,2,3]); te_mask=(day_all==4)
mu,sd=zscore_fit(Xw[tr_mask]); Xtr=zscore_apply(Xw[tr_mask],mu,sd); Xte=zscore_apply(Xw[te_mask],mu,sd)
ytr,yte=yw[tr_mask],yw[te_mask]
print("train dist:", {CLASS_NAMES[i]:int((ytr==i).sum()) for i in range(5)})
print("test  dist:", {CLASS_NAMES[i]:int((yte==i).sum()) for i in range(5)})
for name in ALL:
    if name=="XGBoost": pred,_=train_eval_xgb(Xtr,ytr,Xte,yte,0)
    else:               pred,_=train_eval_torch(name,Xtr,ytr,Xte,yte,SEQ_LEN,0)
    mt=metrics(yte,pred)
    print(f"  {name:14s} acc={mt['acc']:.4f} macroF1={mt['f1_macro']:.4f} weightedF1={mt['f1_weighted']:.4f}")

# ================= L-SWEEP (MambaKAN-APT, reviewer request) =================
print("\n" + "="*70); print("L-SWEEP — MambaKAN-APT, stratified seed 0"); print("="*70)
for L in L_SWEEP:
    XwL,ywL=causal_windows(X_all,y_all,day_all,L)
    sss=StratifiedShuffleSplit(1,test_size=TEST_FRAC,random_state=0); tr,te=next(sss.split(XwL,ywL))
    mu,sd=zscore_fit(XwL[tr])
    pred,_=train_eval_torch("MambaKAN-APT",zscore_apply(XwL[tr],mu,sd),ywL[tr],
                            zscore_apply(XwL[te],mu,sd),ywL[te],L,0)
    mt=metrics(ywL[te],pred)
    print(f"  L={L:2d}: acc={mt['acc']:.4f} macroF1={mt['f1_macro']:.4f} weightedF1={mt['f1_weighted']:.4f}")

# ============================ SHAP =========================================
print("\n" + "="*70); print("SHAP feature attribution"); print("="*70)
try:
    import shap
    # train one MambaKAN + XGBoost on stratified seed 0 for explanation
    sss=StratifiedShuffleSplit(1,test_size=TEST_FRAC,random_state=0); tr,te=next(sss.split(Xw,yw))
    mu,sd=zscore_fit(Xw[tr]); Xtr=zscore_apply(Xw[tr],mu,sd); Xte=zscore_apply(Xw[te],mu,sd)
    # ---- XGBoost TreeExplainer (exact, fast) over flattened window ----
    import xgboost as xgb
    xgb_pred, xgb_model = train_eval_xgb(Xtr,yw[tr],Xte,yw[te],0)
    expl=shap.TreeExplainer(xgb_model)
    sv=expl.shap_values(Xte[:2000].reshape(2000,-1))           # list per class or array
    sv=np.array(sv); imp=np.abs(sv).reshape(sv.shape[0] if sv.ndim==3 else 1,2000,SEQ_LEN,F_DIM)
    imp=imp.mean(axis=(0,1,2))                                  # -> per original feature
    order=np.argsort(imp)[::-1][:15]
    print("Top-15 features by mean|SHAP| (XGBoost, TreeExplainer, exact):")
    for r in order: print(f"  {feat_cols[r]:35s} {imp[r]:.5f}")
    # ---- MambaKAN GradientExplainer (subsampled) ----
    m=make_model("MambaKAN-APT",SEQ_LEN)
    _=train_eval_torch  # already trained variant not retained; retrain quick for SHAP
    pred,m=train_eval_torch("MambaKAN-APT",Xtr,yw[tr],Xte,yw[te],SEQ_LEN,0)
    bg=torch.tensor(Xtr[np.random.RandomState(0).choice(len(Xtr),100,False)]).to(DEVICE)
    ex=shap.GradientExplainer(m, bg)
    sample=torch.tensor(Xte[:300]).to(DEVICE)
    gsv=ex.shap_values(sample)
    gsv=np.array(gsv); gimp=np.abs(gsv).mean(axis=tuple(range(gsv.ndim-1)))  # per feature
    gorder=np.argsort(gimp)[::-1][:15]
    print("\nTop-15 features by mean|SHAP| (MambaKAN-APT, GradientExplainer):")
    for r in gorder: print(f"  {feat_cols[r]:35s} {gimp[r]:.5f}")
except Exception as e:
    print("SHAP step failed (report this if needed):", repr(e))

print("\nDONE.")

# ====== CELL 3: XAI — SHAP + LIME on DAPT 2020 flows (inline, no saving) ======
import numpy as np, matplotlib.pyplot as plt, torch
from sklearn.model_selection import StratifiedShuffleSplit
import shap, xgboost as xgb
from lime.lime_tabular import LimeTabularExplainer

# ---- 1. one stratified split + leakage-free z-score (fit on TRAIN only) ----
sss = StratifiedShuffleSplit(1, test_size=TEST_FRAC, random_state=0)
tr, te = next(sss.split(Xw, yw))
mu, sd = zscore_fit(Xw[tr])
Xtr = zscore_apply(Xw[tr], mu, sd)
Xte = zscore_apply(Xw[te], mu, sd)
ytr, yte = yw[tr], yw[te]
feat = np.array(feat_cols)

# flattened (window x feature) views for tree models
Xtr_flat = Xtr.reshape(len(Xtr), -1)
Xte_flat = Xte.reshape(len(Xte), -1)

# ---- 2. XGBoost SHAP (TreeExplainer, exact) -> collapse window dim to per-feature ----
xgb_model = xgb.XGBClassifier(n_estimators=400, max_depth=8, learning_rate=0.1,
    subsample=0.8, colsample_bytree=0.8, tree_method="hist", device=DEVICE,
    objective="multi:softprob", num_class=5, eval_metric="mlogloss", random_state=0)
xgb_model.fit(Xtr_flat, ytr)

NS = min(2000, len(Xte_flat))
sv = np.array(shap.TreeExplainer(xgb_model).shap_values(Xte_flat[:NS]))   # (NC,NS,L*F) or (NS,L*F)
if sv.ndim == 2: sv = sv[None]                                           # -> (1,NS,L*F)
# (NC, NS, L*F) -> mean|.| over classes,samples,window -> per original feature
imp = np.abs(sv).reshape(sv.shape[0], NS, SEQ_LEN, F_DIM).mean(axis=(0,1,2))
order = np.argsort(imp)[::-1][:15]

plt.figure(figsize=(8,6))
plt.barh(range(len(order)), imp[order][::-1], color="#2c7fb8")
plt.yticks(range(len(order)), feat[order][::-1], fontsize=9)
plt.xlabel("mean |SHAP value|  (collapsed over window L)")
plt.title("SHAP — Top-15 DAPT flow features (XGBoost, TreeExplainer exact)")
plt.tight_layout(); plt.show()

# ---- 3. MambaKAN SHAP (GradientExplainer) -> per-feature over window ----
pred, m = train_eval_torch("MambaKAN-APT", Xtr, ytr, Xte, yte, SEQ_LEN, 0)
m.eval()
bg = torch.tensor(Xtr[np.random.RandomState(0).choice(len(Xtr), 100, False)]).to(DEVICE)
sample = torch.tensor(Xte[:300]).to(DEVICE)
gsv = np.array(shap.GradientExplainer(m, bg).shap_values(sample))   # (NC,300,L,F) or (300,L,F)
gimp = np.abs(gsv).mean(axis=tuple(range(gsv.ndim-1)))              # -> (F,)
gorder = np.argsort(gimp)[::-1][:15]

plt.figure(figsize=(8,6))
plt.barh(range(len(gorder)), gimp[gorder][::-1], color="#41ab5d")
plt.yticks(range(len(gorder)), feat[gorder][::-1], fontsize=9)
plt.xlabel("mean |SHAP value|")
plt.title("SHAP — Top-15 DAPT flow features (MambaKAN-APT, GradientExplainer)")
plt.tight_layout(); plt.show()

# ---- 4. LIME (tabular, on the last flow of each window) ----
# LIME explains the most recent flow (t = -1) since that is the target step.
Xtr_last = Xtr[:, -1, :]           # (N, F) normalized last-step features
Xte_last = Xte[:, -1, :]

def predict_proba_last(z):
    # z: (n, F) last-step rows -> rebuild full windows by repeating across L
    zz = np.repeat(z[:, None, :], SEQ_LEN, axis=1).astype(np.float32)
    with torch.no_grad():
        out = m(torch.tensor(zz).to(DEVICE))
        return torch.softmax(out, 1).cpu().numpy()

explainer = LimeTabularExplainer(
    Xtr_last, feature_names=list(feat), class_names=CLASS_NAMES,
    discretize_continuous=True, mode="classification", random_state=0)

# explain one correctly-classified flow from the rarest predicted class with support
cls_focus = int(np.bincount(yte).argmax())
cand = [j for j in range(len(Xte_last))
        if yte[j] == cls_focus and m(torch.tensor(Xte[j:j+1]).to(DEVICE)).argmax(1).item() == cls_focus]
idx = cand[0] if cand else 0
exp = explainer.explain_instance(Xte_last[idx], predict_proba_last,
                                 num_features=12, labels=(cls_focus,))

pairs = exp.as_list(label=cls_focus)
words = [w for w,_ in pairs][::-1]; weights = [v for _,v in pairs][::-1]
colors = ["#d7191c" if v < 0 else "#1a9641" for v in weights]
plt.figure(figsize=(8,6))
plt.barh(range(len(words)), weights, color=colors)
plt.yticks(range(len(words)), words, fontsize=8)
plt.axvline(0, color="k", lw=0.6)
plt.xlabel("LIME weight")
plt.title(f"LIME — local explanation (class={CLASS_NAMES[cls_focus]}, MambaKAN-APT)")
plt.tight_layout(); plt.show()

print("\nXAI done — XGBoost SHAP bar + MambaKAN SHAP bar + LIME local explanation rendered inline.")

"""### SHAP Top Opcode N-Grams (XGBoost) — CyberScienceLab

![SHAP CyberScienceLab Top Opcode N-Grams](/content/figs_csl/fig_shap_csl.png)
"""

# Download the zip file
files.download(f'{/content/csl_xai_outputs}.zip')

"""## SHAP Feature Attributions (DAPT 2020)"""

import matplotlib.pyplot as plt
import numpy as np

# Ensure that feat_cols, shap_xgb, and shap_mk are available from previous runs
# If you rerun the notebook from scratch, make sure cell JFM7rvNRjtaP has been executed.

if 'shap_xgb' in globals() and 'shap_mk' in globals() and 'feat_cols' in globals():
    fig, axes = plt.subplots(1, 2, figsize=(14, 7))
    fig.suptitle('Top-15 SHAP Features (DAPT 2020)', fontsize=16)

    # Plot for XGBoost
    if shap_xgb is not None:
        o_xgb = np.argsort(shap_xgb)[::-1][:15]
        axes[0].barh([feat_cols[i] for i in o_xgb][::-1], shap_xgb[o_xgb][::-1], color="indianred")
        axes[0].set_xlabel("Mean Absolute SHAP Value")
        axes[0].set_title("XGBoost")
        axes[0].tick_params(axis='y', labelsize=8)

    # Plot for MambaKAN-APT
    if shap_mk is not None:
        o_mk = np.argsort(shap_mk)[::-1][:15]
        axes[1].barh([feat_cols[i] for i in o_mk][::-1], shap_mk[o_mk][::-1], color="steelblue")
        axes[1].set_xlabel("Mean Absolute SHAP Value")
        axes[1].set_title("MambaKAN-APT")
        axes[1].tick_params(axis='y', labelsize=8)

    plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to prevent suptitle overlap
    plt.show()
else:
    print("SHAP values or feature names are not available. Please ensure the relevant cells have been executed.")

# ====== FINAL CyberScienceLab CELL: results + SHAP + figures (one run) ========
# Reuses from the CSL Cell 2 (must be run this session): opcode_lists,
# opcode_strings, y_all, classes, NC, build_vocab, to_ids, train_seq, train_tab,
# SEQ_LEN, VOCAB, NGRAM_MAXFEAT, ALL, SEQ_MODELS.
assert 'opcode_lists' in globals() and 'train_seq' in globals(), \
    "Run the CyberScienceLab Cell 2 first (defines data + models)."

import os, numpy as np, json
import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (classification_report, accuracy_score, f1_score,
                             confusion_matrix)
from scipy import stats
FIG = "/content/figs_csl"; os.makedirs(FIG, exist_ok=True)
NFOLDS = 5; yarr = y_all

skf = StratifiedKFold(NFOLDS, shuffle=True, random_state=0)
res = {m: {"acc":[], "mf1":[], "wf1":[], "perclass":[]} for m in ALL}
mk_true, mk_pred = [], []
for fold, (tr, te) in enumerate(skf.split(np.zeros(len(yarr)), yarr)):
    vocab = build_vocab([opcode_lists[i] for i in tr], VOCAB)
    Xseq_tr = to_ids([opcode_lists[i] for i in tr], vocab, SEQ_LEN)
    Xseq_te = to_ids([opcode_lists[i] for i in te], vocab, SEQ_LEN)
    vec = CountVectorizer(ngram_range=(1,2), max_features=NGRAM_MAXFEAT, token_pattern=r"[^\s]+")
    Xng_tr = vec.fit_transform([opcode_strings[i] for i in tr]).toarray().astype(np.float32)
    Xng_te = vec.transform([opcode_strings[i] for i in te]).toarray().astype(np.float32)
    ytr, yte = yarr[tr], yarr[te]
    for name in ALL:
        if name in SEQ_MODELS: pred = train_seq(name, Xseq_tr, ytr, Xseq_te, VOCAB, SEQ_LEN, fold)
        else:                  pred, _ = train_tab(name, Xng_tr, ytr, Xng_te, fold)
        res[name]["acc"].append(accuracy_score(yte, pred))
        res[name]["mf1"].append(f1_score(yte, pred, average="macro", zero_division=0))
        res[name]["wf1"].append(f1_score(yte, pred, average="weighted", zero_division=0))
        rep = classification_report(yte, pred, labels=list(range(NC)), target_names=classes,
                                    output_dict=True, zero_division=0)
        res[name]["perclass"].append([rep[c]["f1-score"] for c in classes])
        if name == "MambaKAN-APT": mk_true += list(yte); mk_pred += list(pred)

# ---------------- summary + significance ----------------
print(f"{'model':16s}{'accuracy':>16s}{'macro-F1':>16s}{'weighted-F1':>16s}")
summary = {}
for name in ALL:
    a=np.array(res[name]['acc']); m=np.array(res[name]['mf1']); w=np.array(res[name]['wf1'])
    summary[name] = {"acc":[a.mean(),a.std()], "mf1":[m.mean(),m.std()], "wf1":[w.mean(),w.std()]}
    print(f"{name:16s}{a.mean():.4f}±{a.std():.4f}  {m.mean():.4f}±{m.std():.4f}  {w.mean():.4f}±{w.std():.4f}")
base=[b for b in ALL if b!="MambaKAN-APT"]; best=max(base,key=lambda b:np.mean(res[b]['mf1']))
t,p=stats.ttest_rel(res["MambaKAN-APT"]['mf1'], res[best]['mf1'])
print(f"\nsignificance (paired t, macro-F1): MambaKAN-APT vs {best}: t={t:.3f} p={p:.4f}")
mk_pc = np.array(res["MambaKAN-APT"]["perclass"])
print("per-class F1 (MambaKAN, mean±std):")
for j,c in enumerate(classes): print(f"  {c:14s} {mk_pc[:,j].mean():.3f}±{mk_pc[:,j].std():.3f}")

# ---------------- SHAP (opcode n-grams, exact TreeExplainer) ----------------
shap_imp = shap_feat = None
try:
    import shap
    tr = np.arange(len(yarr))[: int(0.8*len(yarr))]; te = np.arange(len(yarr))[int(0.8*len(yarr)):]
    vec = CountVectorizer(ngram_range=(1,2), max_features=NGRAM_MAXFEAT, token_pattern=r"[^\s]+")
    Xtr = vec.fit_transform([opcode_strings[i] for i in tr]).toarray().astype(np.float32)
    Xte = vec.transform([opcode_strings[i] for i in te]).toarray().astype(np.float32)
    shap_feat = np.array(vec.get_feature_names_out())
    _, clf = train_tab("XGBoost(ngram)", Xtr, yarr[tr], Xte, 0)
    sv = np.array(shap.TreeExplainer(clf).shap_values(Xte))
    shap_imp = np.abs(sv).mean(axis=tuple(range(sv.ndim-1)))
    print("\nTop-15 SHAP opcode n-grams (XGBoost):")
    for r in np.argsort(shap_imp)[::-1][:15]: print(f"  {shap_feat[r]:22s}{shap_imp[r]:.5f}")
except Exception as e:
    print("SHAP failed:", repr(e))

# ---------------- FIGURES ----------------
def save(fig, n): fig.tight_layout(); fig.savefig(f"{FIG}/{n}", dpi=200); plt.close(fig); print("saved", n)

# 1. confusion matrix (pooled CV, MambaKAN)
cm = confusion_matrix(mk_true, mk_pred, labels=list(range(NC)))
cmn = cm / cm.sum(1, keepdims=True).clip(min=1)
fig,ax=plt.subplots(figsize=(6,5)); im=ax.imshow(cmn,cmap="Purples",vmin=0,vmax=1)
ax.set_xticks(range(NC)); ax.set_yticks(range(NC))
ax.set_xticklabels(classes,rotation=45,ha="right"); ax.set_yticklabels(classes)
for i in range(NC):
    for j in range(NC): ax.text(j,i,f"{cmn[i,j]:.2f}",ha="center",va="center",
        color="white" if cmn[i,j]>0.5 else "black",fontsize=8)
ax.set_xlabel("Predicted"); ax.set_ylabel("True"); ax.set_title("MambaKAN-APT — CyberScienceLab (5-fold CV)")
plt.colorbar(im); save(fig,"fig_confusion_csl.png")

# 2. model macro-F1 comparison
fig,ax=plt.subplots(figsize=(7,4)); xs=range(len(ALL))
ax.bar(xs,[summary[n]["mf1"][0] for n in ALL],yerr=[summary[n]["mf1"][1] for n in ALL],capsize=4,color="mediumpurple")
ax.set_xticks(xs); ax.set_xticklabels(ALL,rotation=30,ha="right"); ax.set_ylabel("Macro-F1")
ax.set_ylim(0,1); ax.set_title("Macro-F1 (mean±std, 5-fold) — CyberScienceLab"); save(fig,"fig_macrof1_csl.png")

# 3. per-class F1 (MambaKAN)
fig,ax=plt.subplots(figsize=(7,4))
ax.bar(range(NC),mk_pc.mean(0),yerr=mk_pc.std(0),capsize=4,color="teal")
ax.set_xticks(range(NC)); ax.set_xticklabels(classes,rotation=30,ha="right")
ax.set_ylabel("F1"); ax.set_ylim(0,1); ax.set_title("MambaKAN-APT per-class F1 — CyberScienceLab"); save(fig,"fig_perclass_csl.png")

# 4. SHAP top opcodes
if shap_imp is not None:
    o=np.argsort(shap_imp)[::-1][:15]
    fig,ax=plt.subplots(figsize=(7,5)); ax.barh([shap_feat[i] for i in o][::-1],shap_imp[o][::-1],color="indianred")
    ax.set_xlabel("mean |SHAP|"); ax.set_title("Top-15 opcode n-grams (XGBoost) — CyberScienceLab"); save(fig,"fig_shap_csl.png")

json.dump({"summary":summary,"sig":{"vs":best,"t":t,"p":p},
           "perclass_mk":{classes[j]:[mk_pc[:,j].mean(),mk_pc[:,j].std()] for j in range(NC)}},
          open(f"{FIG}/results_csl.json","w"), indent=2)
print(f"\nALL DONE. Figures + results_csl.json in {FIG}")

# ============ CELL 1: get CyberScienceLab APT (opcode views) ===============
!pip -q install shap xgboost scikit-learn scipy 2>/dev/null
!apt-get -qq install unrar git-lfs >/dev/null 2>&1; git lfs install >/dev/null 2>&1

import os, glob
ROOT = "/content/csl"
REPO = f"{ROOT}/Our-Datasets"
os.makedirs(ROOT, exist_ok=True)
if not os.path.isdir(REPO):
    !git clone --filter=blob:none https://github.com/CyberScienceLab/Our-Datasets.git {REPO}
# pull only the APT multi-part RAR (LFS) + keep the label csv
!cd {REPO} && git lfs pull --include="APT/apt_views.part0*.rar" 2>/dev/null || true

APT = f"{REPO}/APT"
EXTRACT = f"{ROOT}/extracted"
os.makedirs(EXTRACT, exist_ok=True)
parts = sorted(glob.glob(f"{APT}/apt_views.part0*.rar"))
print("RAR parts:", [(os.path.basename(p), f"{os.path.getsize(p)/1e6:.0f}MB") for p in parts])
# unrar auto-joins multi-volume when pointed at part01
!unrar x -o+ "{APT}/apt_views.part01.rar" "{EXTRACT}/" >/dev/null 2>&1 || \
 unrar x -o+ "{APT}/apt_views.part01.rar" "{EXTRACT}/"

opc = glob.glob(f"{EXTRACT}/**/opcode-*.txt", recursive=True)
print(f"extracted opcode files: {len(opc)}")
print("label file exists:", os.path.exists(f"{APT}/APTfileList.csv"))
os.environ["CSL_EXTRACT"] = EXTRACT
os.environ["CSL_LABELS"] = f"{APT}/APTfileList.csv"

# ====== CELL 2: MambaKAN-APT on CyberScienceLab opcode sequences ===========
import os, glob, re, time, warnings, numpy as np, torch
import torch.nn as nn, torch.nn.functional as F
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import classification_report, accuracy_score, f1_score
from sklearn.model_selection import StratifiedShuffleSplit
from scipy import stats
warnings.filterwarnings("ignore")
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", DEVICE)

# ---------------- CONFIG ----------------
EXTRACT = os.environ.get("CSL_EXTRACT", "/content/csl/extracted")
LABELS  = os.environ.get("CSL_LABELS", "/content/csl/Our-Datasets/APT/APTfileList.csv")
SEEDS   = [0,1,2,3,4]
EPOCHS  = 30
BATCH   = 64
SEQ_LEN = 512          # opcode tokens per sample (truncate/pad)
VOCAB   = 200          # top-V opcodes (rest -> UNK); 0=PAD
EMB     = 64
NGRAM_MAXFEAT = 2000   # for classical baselines

# ---------------- 1. LOAD opcode views + labels ----------------
def load_labels(path):
    lab = {}
    with open(path, "r", errors="replace") as fh:
        for line in fh:
            parts = line.strip().split(",")
            if len(parts) < 2: continue
            h, g = parts[0].strip().lower(), parts[1].strip()
            if re.fullmatch(r"[0-9a-f]{64}", h):   # valid sha256 only
                lab[h] = g
    return lab

labels = load_labels(LABELS)
hash_re = re.compile(r"([0-9a-f]{64})", re.I)
samples = []   # (hash, opcode_string, label)
for f in glob.glob(f"{EXTRACT}/**/opcode-*.txt", recursive=True):
    m = hash_re.search(os.path.basename(f))
    if not m: continue
    h = m.group(1).lower()
    if h not in labels: continue
    with open(f, "r", errors="replace") as fh:
        toks = fh.read().split()
    if len(toks) < 5: continue
    samples.append((h, toks, labels[h]))

classes = sorted(set(s[2] for s in samples))
cls2id = {c:i for i,c in enumerate(classes)}
y_all = np.array([cls2id[s[2]] for s in samples], dtype=np.int64)
opcode_lists = [s[1] for s in samples]
opcode_strings = [" ".join(t) for t in opcode_lists]
NC = len(classes)
print(f"samples={len(samples)}  classes({NC})={classes}")
print("class dist:", {c:int((y_all==cls2id[c]).sum()) for c in classes})
print("median opcode length:", int(np.median([len(t) for t in opcode_lists])))

# ---------------- 2. encoders (fit on TRAIN fold only) ----------------
def build_vocab(train_lists, V):
    from collections import Counter
    cnt = Counter()
    for t in train_lists: cnt.update(t)
    top = [w for w,_ in cnt.most_common(V-2)]      # reserve 0=PAD,1=UNK
    return {w:i+2 for i,w in enumerate(top)}

def to_ids(lists, vocab, L):
    out = np.zeros((len(lists), L), dtype=np.int64)
    for i,t in enumerate(lists):
        ids = [vocab.get(w,1) for w in t[:L]]
        out[i,:len(ids)] = ids
    return out

# ---------------- 3. MODELS (token-embedding front end) ----------------
class BSpline(nn.Module):
    def __init__(s,n=8,d=3):
        super().__init__(); s.d=d; s.register_buffer("k",torch.linspace(-1,1,n+d+1))
    def forward(s,x):
        x=x.unsqueeze(-1); k=s.k; b=((x>=k[:-1])&(x<k[1:])).float()
        for j in range(1,s.d+1):
            ln=x-k[:-(j+1)]; ld=(k[j:-1]-k[:-(j+1)]).clamp(min=1e-8)
            rn=k[j+1:]-x;    rd=(k[j+1:]-k[1:(-j if j>0 else None)]).clamp(min=1e-8)
            b=(ln/ld)*b[...,:-1]+(rn/rd)*b[...,1:]
        return b
class KANLayer(nn.Module):
    def __init__(s,i,o,n=8):
        super().__init__(); s.bs=BSpline(n); s.c=nn.Parameter(torch.randn(i,o,n)*0.1)
        s.lin=nn.Linear(i,o); s.nm=nn.LayerNorm(o)
    def forward(s,x):
        return s.nm(torch.einsum("bin,ion->bo",s.bs(torch.tanh(x)),s.c)+F.silu(s.lin(x)))
class SelectiveSSM(nn.Module):
    def __init__(s,dm,ds=16,dc=4,ex=2):
        super().__init__(); s.di=dm*ex; s.ds=ds
        s.inp=nn.Linear(dm,s.di*2,bias=False)
        s.cv=nn.Conv1d(s.di,s.di,dc,padding=dc-1,groups=s.di,bias=True)
        s.xp=nn.Linear(s.di,ds*2+1,bias=False); s.dtp=nn.Linear(1,s.di,bias=True)
        A=torch.arange(1,ds+1,dtype=torch.float32).unsqueeze(0).expand(s.di,-1)
        s.Al=nn.Parameter(torch.log(A.clone())); s.D=nn.Parameter(torch.ones(s.di))
        s.op=nn.Linear(s.di,dm,bias=False); s.nm=nn.LayerNorm(dm)
    def forward(s,x):
        B,L,_=x.shape; res=x; xc,z=s.inp(x).chunk(2,-1)
        xc=F.silu(s.cv(xc.transpose(1,2))[:,:,:L].transpose(1,2))
        p=s.xp(xc); Bp=p[:,:,:s.ds]; Cp=p[:,:,s.ds:2*s.ds]
        dt=F.softplus(s.dtp(p[:,:,-1:])); A=-torch.exp(s.Al)
        h=torch.zeros(B,s.di,s.ds,device=x.device); outs=[]
        for t in range(L):                              # TRUE recurrence
            dA=torch.exp(A.unsqueeze(0)*dt[:,t,:].unsqueeze(-1))
            dB=dt[:,t,:].unsqueeze(-1)*Bp[:,t,:].unsqueeze(1)
            h=dA*h+dB*xc[:,t,:].unsqueeze(-1)
            outs.append((h*Cp[:,t,:].unsqueeze(1)).sum(-1)+s.D*xc[:,t,:])
        return s.nm(s.op(torch.stack(outs,1)*F.silu(z))+res)
class MambaBlock(nn.Module):
    def __init__(s,dm,ds=16):
        super().__init__(); s.ssm=SelectiveSSM(dm,ds)
        s.ffn=nn.Sequential(nn.Linear(dm,dm*2),nn.GELU(),nn.Dropout(0.1),nn.Linear(dm*2,dm)); s.nm=nn.LayerNorm(dm)
    def forward(s,x): x=s.ssm(x); return s.nm(x+s.ffn(x))
class MambaKAN(nn.Module):
    def __init__(s,V,nc,L,dm=64,nl=2,ds=16):
        super().__init__(); s.emb=nn.Embedding(V,EMB,padding_idx=0)
        s.kan=KANLayer(EMB,dm); s.pos=nn.Parameter(torch.randn(1,L,dm)*0.02)
        s.mb=nn.ModuleList([MambaBlock(dm,ds) for _ in range(nl)])
        s.cl=nn.Sequential(nn.Linear(dm*2,128),nn.GELU(),nn.Dropout(0.3),nn.Linear(128,nc))
    def forward(s,x):
        B,L=x.shape; e=s.kan(s.emb(x).reshape(B*L,EMB)).reshape(B,L,-1)+s.pos[:,:L,:]
        for m in s.mb: e=m(e)
        return s.cl(torch.cat([e.mean(1),e.max(1).values],-1))
class LSTMcls(nn.Module):
    def __init__(s,V,nc):
        super().__init__(); s.emb=nn.Embedding(V,EMB,padding_idx=0)
        s.l=nn.LSTM(EMB,64,2,batch_first=True,dropout=0.1,bidirectional=True)
        s.c=nn.Sequential(nn.Linear(128,64),nn.ReLU(),nn.Dropout(0.3),nn.Linear(64,nc))
    def forward(s,x): o,_=s.l(s.emb(x)); return s.c(o[:,-1,:])
class TransformerCls(nn.Module):
    def __init__(s,V,nc,L):
        super().__init__(); s.emb=nn.Embedding(V,EMB,padding_idx=0)
        s.pos=nn.Parameter(torch.randn(1,L,EMB)*0.02)
        s.t=nn.TransformerEncoder(nn.TransformerEncoderLayer(EMB,4,128,0.1,batch_first=True),2)
        s.c=nn.Sequential(nn.Linear(EMB,64),nn.ReLU(),nn.Dropout(0.3),nn.Linear(64,nc))
    def forward(s,x): return s.c(s.t(s.emb(x)+s.pos[:,:x.shape[1],:]).mean(1))
class FocalLoss(nn.Module):
    def __init__(s,a=None,g=2.0): super().__init__(); s.a=a; s.g=g
    def forward(s,o,t):
        ce=F.cross_entropy(o,t,weight=s.a,reduction="none"); pt=torch.exp(-ce)
        return (((1-pt)**s.g)*ce).mean()

SEQ_MODELS = ["MambaKAN-APT","LSTM","Transformer"]
ALL = SEQ_MODELS + ["SAE(ngram)","XGBoost(ngram)"]

def make_seq_model(name,V,L):
    if name=="MambaKAN-APT": return MambaKAN(V,NC,L)
    if name=="LSTM":         return LSTMcls(V,NC)
    if name=="Transformer":  return TransformerCls(V,NC,L)

def train_seq(name,Xtr,ytr,Xte,V,L,seed):
    torch.manual_seed(seed); np.random.seed(seed)
    m=make_seq_model(name,V,L).to(DEVICE)
    cw=torch.tensor([len(ytr)/(NC*max(1,(ytr==c).sum())) for c in range(NC)],
                    dtype=torch.float32,device=DEVICE)
    crit=FocalLoss(cw,2.0); opt=torch.optim.AdamW(m.parameters(),1e-3,weight_decay=1e-4)
    sch=torch.optim.lr_scheduler.CosineAnnealingLR(opt,T_max=EPOCHS,eta_min=1e-6)
    Xt=torch.tensor(Xtr); yt=torch.tensor(ytr); n=len(Xt)
    for ep in range(EPOCHS):
        m.train(); perm=torch.randperm(n)
        for i in range(0,n,BATCH):
            b=perm[i:i+BATCH]; opt.zero_grad()
            loss=crit(m(Xt[b].to(DEVICE)), yt[b].to(DEVICE)); loss.backward()
            nn.utils.clip_grad_norm_(m.parameters(),1.0); opt.step()
        sch.step()
    m.eval(); preds=[]
    with torch.no_grad():
        Xe=torch.tensor(Xte)
        for i in range(0,len(Xe),BATCH): preds.append(m(Xe[i:i+BATCH].to(DEVICE)).argmax(1).cpu().numpy())
    return np.concatenate(preds)

def train_tab(name,Xtr,ytr,Xte,seed):
    if name=="XGBoost(ngram)":
        import xgboost as xgb
        clf=xgb.XGBClassifier(n_estimators=400,max_depth=6,learning_rate=0.1,subsample=0.8,
            colsample_bytree=0.8,tree_method="hist",device=DEVICE,objective="multi:softprob",
            num_class=NC,eval_metric="mlogloss",random_state=seed)
        clf.fit(Xtr,ytr); return clf.predict(Xte), clf
    else:  # SAE on ngram counts
        torch.manual_seed(seed)
        D=Xtr.shape[1]
        m=nn.Sequential(nn.Linear(D,256),nn.ReLU(),nn.Dropout(0.3),nn.Linear(256,64),
                        nn.ReLU(),nn.Dropout(0.2),nn.Linear(64,NC)).to(DEVICE)
        cw=torch.tensor([len(ytr)/(NC*max(1,(ytr==c).sum())) for c in range(NC)],dtype=torch.float32,device=DEVICE)
        crit=FocalLoss(cw,2.0); opt=torch.optim.AdamW(m.parameters(),1e-3,weight_decay=1e-4)
        Xt=torch.tensor(Xtr,dtype=torch.float32); yt=torch.tensor(ytr)
        for ep in range(EPOCHS):
            perm=torch.randperm(len(Xt))
            for i in range(0,len(Xt),BATCH):
                b=perm[i:i+BATCH]; opt.zero_grad()
                crit(m(Xt[b].to(DEVICE)),yt[b].to(DEVICE)).backward(); opt.step()
        m.eval()
        with torch.no_grad(): pr=m(torch.tensor(Xte,dtype=torch.float32).to(DEVICE)).argmax(1).cpu().numpy()
        return pr, m

def metrics(yte,pred):
    rep=classification_report(yte,pred,labels=list(range(NC)),target_names=classes,
                              output_dict=True,zero_division=0)
    return {"acc":accuracy_score(yte,pred),
            "f1_macro":f1_score(yte,pred,average="macro",zero_division=0),
            "f1_weighted":f1_score(yte,pred,average="weighted",zero_division=0),"report":rep}

# ---------------- 4. 5-seed stratified CV ----------------
print("\n"+"="*70+"\nCyberScienceLab APT attribution — stratified, 5 seeds\n"+"="*70)
res={k:{"acc":[],"f1_macro":[],"f1_weighted":[]} for k in ALL}
last_rep={}
yarr=y_all
for seed in SEEDS:
    sss=StratifiedShuffleSplit(1,test_size=0.2,random_state=seed)
    tr,te=next(sss.split(np.zeros(len(yarr)),yarr))
    # leakage-free encoders fit on TRAIN only
    vocab=build_vocab([opcode_lists[i] for i in tr],VOCAB)
    Xseq_tr=to_ids([opcode_lists[i] for i in tr],vocab,SEQ_LEN)
    Xseq_te=to_ids([opcode_lists[i] for i in te],vocab,SEQ_LEN)
    vec=CountVectorizer(ngram_range=(1,2),max_features=NGRAM_MAXFEAT,token_pattern=r"[^\s]+")
    Xng_tr=vec.fit_transform([opcode_strings[i] for i in tr]).toarray().astype(np.float32)
    Xng_te=vec.transform([opcode_strings[i] for i in te]).toarray().astype(np.float32)
    ytr,yte=yarr[tr],yarr[te]
    for name in ALL:
        t0=time.time()
        if name in SEQ_MODELS: pred=train_seq(name,Xseq_tr,ytr,Xseq_te,VOCAB,SEQ_LEN,seed)
        else:                  pred,_=train_tab(name,Xng_tr,ytr,Xng_te,seed)
        mt=metrics(yte,pred)
        for k in ("acc","f1_macro","f1_weighted"): res[name][k].append(mt[k])
        last_rep[name]=mt["report"]
        print(f"  seed {seed} {name:16s} acc={mt['acc']:.4f} macroF1={mt['f1_macro']:.4f} ({time.time()-t0:.0f}s)")

print("\n----- SUMMARY (mean ± std over %d seeds) -----"%len(SEEDS))
print(f"{'model':16s} {'accuracy':>16s} {'macro-F1':>16s} {'weighted-F1':>16s}")
for name in ALL:
    a=np.array(res[name]['acc']); fm=np.array(res[name]['f1_macro']); fw=np.array(res[name]['f1_weighted'])
    print(f"{name:16s} {a.mean():.4f}±{a.std():.4f}  {fm.mean():.4f}±{fm.std():.4f}  {fw.mean():.4f}±{fw.std():.4f}")

base=[b for b in ALL if b!="MambaKAN-APT"]
best=max(base,key=lambda b: np.mean(res[b]['f1_macro']))
t,p=stats.ttest_rel(res["MambaKAN-APT"]['f1_macro'],res[best]['f1_macro'])
print(f"\nSignificance (paired t, macro-F1): MambaKAN-APT vs {best}: t={t:.3f}, p={p:.4f} (n={len(SEEDS)})")
print("\nPer-class (last seed, MambaKAN-APT) — with SUPPORT:")
for c in classes:
    r=last_rep["MambaKAN-APT"][c]
    print(f"  {c:14s} P={r['precision']:.3f} R={r['recall']:.3f} F1={r['f1-score']:.3f} support={int(r['support'])}")

# ---------------- 5. SHAP (XGBoost on opcode n-grams; exact) ----------------
print("\n"+"="*70+"\nSHAP — most discriminative opcode n-grams (XGBoost TreeExplainer)\n"+"="*70)
try:
    import shap, xgboost as xgb
    sss=StratifiedShuffleSplit(1,test_size=0.2,random_state=0); tr,te=next(sss.split(np.zeros(len(yarr)),yarr))
    vec=CountVectorizer(ngram_range=(1,2),max_features=NGRAM_MAXFEAT,token_pattern=r"[^\s]+")
    Xtr=vec.fit_transform([opcode_strings[i] for i in tr]).toarray().astype(np.float32)
    Xte=vec.transform([opcode_strings[i] for i in te]).toarray().astype(np.float32)
    feat=np.array(vec.get_feature_names_out())
    _,clf=train_tab("XGBoost(ngram)",Xtr,yarr[tr],Xte,0)
    sv=np.array(shap.TreeExplainer(clf).shap_values(Xte))
    imp=np.abs(sv).mean(axis=tuple(range(sv.ndim-1)))
    for r in np.argsort(imp)[::-1][:20]:
        print(f"  {feat[r]:25s} {imp[r]:.5f}")
except Exception as e:
    print("SHAP failed:", repr(e))
print("\nDONE.")

pip install lime

# ====== CELL 3: XAI — SHAP + LIME on opcode n-grams (inline plots, no saving) ======
import numpy as np, matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import StratifiedShuffleSplit
import shap, xgboost as xgb
from lime.lime_text import LimeTextExplainer

# ---- 1. one stratified split + leakage-free n-gram encoder ----
sss = StratifiedShuffleSplit(1, test_size=0.2, random_state=0)
tr, te = next(sss.split(np.zeros(len(y_all)), y_all))
vec = CountVectorizer(ngram_range=(1,2), max_features=NGRAM_MAXFEAT, token_pattern=r"[^\s]+")
Xtr = vec.fit_transform([opcode_strings[i] for i in tr]).toarray().astype(np.float32)
Xte = vec.transform([opcode_strings[i] for i in te]).toarray().astype(np.float32)
feat = np.array(vec.get_feature_names_out())
ytr, yte = y_all[tr], y_all[te]

clf = xgb.XGBClassifier(n_estimators=400, max_depth=6, learning_rate=0.1, subsample=0.8,
        colsample_bytree=0.8, tree_method="hist", device=DEVICE, objective="multi:softprob",
        num_class=NC, eval_metric="mlogloss", random_state=0)
clf.fit(Xtr, ytr)

# ---- 2. SHAP (TreeExplainer, exact) ----
expl = shap.TreeExplainer(clf)
sv = expl.shap_values(Xte)                       # list[NC] or array (N,F,NC)
sv = np.array(sv)
if sv.ndim == 3 and sv.shape[0] != NC:           # (N,F,NC) -> (NC,N,F)
    sv = sv.transpose(2,0,1)

# 2a. global bar — top opcode n-grams (mean |SHAP| across all classes/samples)
imp = np.abs(sv).mean(axis=tuple(range(sv.ndim-1)))
order = np.argsort(imp)[::-1][:20]
plt.figure(figsize=(8,6))
plt.barh(range(len(order)), imp[order][::-1], color="#2c7fb8")
plt.yticks(range(len(order)), feat[order][::-1], fontsize=9)
plt.xlabel("mean |SHAP value|"); plt.title("SHAP — Top-20 discriminative opcode n-grams (global)")
plt.tight_layout(); plt.show()

# 2b. per-class beeswarm for the class with most test support
cls_focus = int(np.bincount(yte).argmax())
shap.summary_plot(sv[cls_focus], Xte, feature_names=feat, max_display=15,
                  show=True, plot_size=(8,6))
print(f"[SHAP beeswarm above] class = {classes[cls_focus]}")

# ---- 3. LIME (text explainer on raw opcode strings) ----
def predict_proba(texts):
    X = vec.transform(texts).toarray().astype(np.float32)
    return clf.predict_proba(X)

explainer = LimeTextExplainer(class_names=classes, split_expression=r"\s+", bow=True)
te_strings = [opcode_strings[i] for i in te]

# explain first correctly-classified sample of the focus class
cand = [j for j in range(len(te)) if yte[j]==cls_focus and clf.predict(Xte[j:j+1])[0]==cls_focus]
idx = cand[0] if cand else 0
exp = explainer.explain_instance(te_strings[idx], predict_proba,
                                 num_features=12, labels=(cls_focus,), num_samples=2000)

pairs = exp.as_list(label=cls_focus)
words = [w for w,_ in pairs][::-1]; weights = [v for _,v in pairs][::-1]
colors = ["#d7191c" if v < 0 else "#1a9641" for v in weights]
plt.figure(figsize=(8,6))
plt.barh(range(len(words)), weights, color=colors)
plt.yticks(range(len(words)), words, fontsize=9)
plt.axvline(0, color="k", lw=0.6)
plt.xlabel("LIME weight"); plt.title(f"LIME — opcode contributions (class={classes[cls_focus]}, sample #{te[idx]})")
plt.tight_layout(); plt.show()

print("\nXAI done — SHAP global bar + per-class beeswarm + LIME local explanation rendered inline.")